name: Deploy Corehunter (Port 3001)

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/corehunter/backend
            git pull origin main
            # On reconstruit l'image et on relance le conteneur
            docker compose up --build -d
            # On nettoie les images orphelines pour économiser l'espace disque
            docker image prune -f